name: Build and Publish storybook to GitHub Pages
on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
      with:
        path: dist/storybook
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}

